#!/usr/bin/env python3
"""Check that requests built by the JS model layer satisfy the real backend schema.

This is the highest-value check available without a browser: it runs the actual
ltx25.schemas.GenerateRequest validator against request bodies generated by
generationRequest.js. It catches contract drift that unit tests cannot, because
the unit tests encode assumptions while this encodes the backend's own rules.

Run from the repository root:

    .venv/bin/python frontend/src/studio/model/schema.conformance.py
"""
import json
import subprocess
import sys
from pathlib import Path

# frontend/src/studio/model/ -> repository root
ROOT = Path(__file__).resolve().parents[4]
sys.path.insert(0, str(ROOT))

# The JS model is ESM; drive it with a small node script that emits JSON.
NODE_SCRIPT = r"""
import { buildGenerationRequest } from './generationRequest.js'

// asset ids must satisfy ^[0-9a-f]{32}$ and LoRA ids must end in .safetensors,
// so the fixtures use realistic values rather than placeholders.
const asset = (id, kind) => ({ id, kind, filename: id + '.bin', size: 1024 })
const A = 'a'.repeat(32), B = 'b'.repeat(32), C = 'c'.repeat(32)
const D = 'd'.repeat(32), E = 'e'.repeat(32), F = 'f'.repeat(32)
const LORA = 'ltx-2.5-22b-ic-lora-dubit.safetensors'

const base = {
  prompt: 'ocean sunset', negativePrompt: 'worst quality',
  width: 768, height: 512, numFrames: 121, fps: 24, steps: 8,
  guidanceScale: 3, seed: 42, batch: 1,
  upscale: true, upscaleMethod: 'latent', decoder: 'vae',
  modalityScale: null, audioGuidanceScale: null,
  loraId: null, loraStrength: 1, range: {},
}

const cases = [
  ['t2av', {}, {}],
  ['i2v', { first: asset(A, 'image') }, {}],
  ['flf2v', { first: asset(A, 'image'), last: asset(B, 'image') }, {}],
  ['a2v', { audio: asset(C, 'audio') }, {}],
  ['t2i', {}, { decoder: 'vae' }],
  ['ref2i', { first: asset(A, 'image') }, { numFrames: 49, range: { framePosition: 'last' } }],
  ['refine_image', { first: asset(A, 'image') }, { range: { strength: 0.8 } }],
  ['condition', { source: asset(D, 'image') }, {}],
  ['iclora', { source: asset(E, 'video') }, { loraId: LORA }],
  ['retake', { source: asset(F, 'video') }, { range: { retakeStart: 0.5, retakeEnd: 3 } }],
  ['extend', { source: asset(F, 'video') }, { range: { extendDirection: 'end', extendSeconds: 5, extendContext: 3 } }],
]

const out = []
for (const [mode, assets, overrides] of cases) {
  const draft = { ...base, ...overrides, mode }
  const body = buildGenerationRequest(draft, assets, 12345, 0)
  out.push({ mode, body })
}
console.log(JSON.stringify(out))
"""

model_dir = Path(__file__).resolve().parent
script = model_dir / "_emit_requests.mjs"
script.write_text(NODE_SCRIPT)
try:
    # cwd must be the model directory so the relative import resolves.
    raw = subprocess.run(
        ["node", str(script)], capture_output=True, text=True, cwd=str(model_dir), timeout=60
    )
finally:
    script.unlink(missing_ok=True)

if raw.returncode != 0:
    print("node failed:", raw.stderr[:800])
    sys.exit(1)

payloads = json.loads(raw.stdout)

# Import the real schema. It pulls in pydantic only; the worker-only deps are not
# touched by importing schemas.
from ltx25.schemas import GenerateRequest  # noqa: E402

failures = []
for item in payloads:
    mode = item["mode"]
    body = item["body"]
    # The schema forbids unknown keys, so drop the one the mock tolerates.
    body.pop("client_token", None)
    try:
        GenerateRequest(**body)
        print(f"  ok   {mode:14s} accepted")
    except Exception as exc:  # noqa: BLE001
        message = str(exc).split("\n")[0]
        # Pydantic surfaces "Extra inputs are not permitted" for unknown fields.
        print(f"  FAIL {mode:14s} {message[:160]}")
        failures.append((mode, message))

print(f"\n{len(payloads) - len(failures)}/{len(payloads)} accepted by the real schema")
if failures:
    print("\nFailing modes:", ", ".join(m for m, _ in failures))
    sys.exit(1)
